import Appbar from "@/components/Appbar/page";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home - Fisio Sync",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">

      <body className={inter.className}>
        <Appbar>
          {children}
        </Appbar>
      </body>
    </html>
  );
}
